### ISSUE TITLE
Opening edit for administrator role produce warning in console

### ISSUE THREAD

**Issue by dimitrov-adrian** [directus/next#475]
On Directus v9.0.0-beta.4

```

12:53:01 ✨ request completed GET 304 /roles/18930510-64b4-4ae6-92c1-695867f1eec6?fields[]=users.first_name&fields[]=users.last_name&fields[]=users.id 79ms
Starting with v2.0.0-beta.1 date-fns doesn't accept strings as date arguments. Please use `parseISO` to parse strings. See: https://git.io/fjule
Error
    at toDate (***/my-project/node_modules/date-fns/toDate/index.js:56:20)
    at Object.format (***/my-project/node_modules/date-fns/format/index.js:387:42)
    at PayloadService.<anonymous> (***/my-project/node_modules/directus/dist/services/payload.js:243:57)
    at Generator.next (<anonymous>)
    at fulfilled (***/my-project/node_modules/directus/dist/services/payload.js:9:58)
12:53:01 🚨 Invalid time value 
RangeError: Invalid time value
    at Object.format (***/my-project/node_modules/date-fns/format/index.js:390:11)
    at PayloadService.<anonymous> (***/my-project/node_modules/directus/dist/services/payload.js:243:57)
    at Generator.next (<anonymous>)
    at fulfilled (***/my-project/node_modules/directus/dist/services/payload.js:9:58)
12:53:01 ✨ request errored GET 500 /revisions?filter=%7B%22collection%22:%7B%22_eq%22:%22directus_roles%22%7D,%22item%22:%7B%22_eq%22:%2218930510-64b4-4ae6-92c1-695867f1eec6%22%7D%7D&fields[]=id&fields[]=data&fields[]=delta&fields[]=collection&fields[]=item&fields[]=activity.action&fields[]=activity.action_on&fields[]=activity.action_by.id&fields[]=activity.action_by.first_name&fields[]=activity.action_by.last_name&fields[]=activity.ip&fields[]=activity.user_agent 80ms
```

**Comment by benhaynes** [comment]
Hey @dimitrov-adrian — which DB/Version is this on?

**Comment by dimitrov-adrian** [comment]
Clear install of v9 beta4 with sqlite database.
