### ISSUE TITLE
Internal error while adding a new file

### ISSUE THREAD

**Issue by danieljwestman** [directus/next#477]
Directus v9.0.0-beta.4
Clean install

When opening the "Add file" modal you get a error in console:

```
error select "directus_files".*, "directus_files"."id" from "directus_files" where "id" in ($1) limit $2 - invalid input syntax for type uuid: "null" 
error: select "directus_files".*, "directus_files"."id" from "directus_files" where "id" in ($1) limit $2 - invalid input syntax for type uuid: "null"
    at Parser.parseErrorMessage (/.../Directus/v9/beta4/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/.../Directus/v9/beta4/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/.../Directus/v9/beta4/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/.../Directus/v9/beta4/node_modules/pg-protocol/dist/index.js:8:42)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at addChunk (_stream_readable.js:307:12)
    at readableAddChunk (_stream_readable.js:282:9)
    at Socket.Readable.push (_stream_readable.js:221:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by benhaynes** [comment]
Hey @danieljwestman — which DB/Version is this on?

**Comment by danieljwestman** [comment]
Ah sorry, PG
