### ISSUE TITLE
Docker image error seeding on restart

### ISSUE THREAD

**Issue by maartenvn** [directus/next#491]
**Directus**: v9.0.0-beta.4
**Node**: docker image version
**MySQL**: Ver 14.14

When starting the docker image for the first time, the database is seeded without an issue. However once restarting the docker image the following error is displayed:

```
Error: Database is already installed
    at Object.<anonymous> (/directus/node_modules/directus/dist/database/seeds/run.js:23:19)
    at Generator.next (<anonymous>)
    at fulfilled (/directus/node_modules/directus/dist/database/seeds/run.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by WoLfulus** [comment]
that should have been treated though. I'll check why it's not catching
