### ISSUE TITLE
Cannot upload file in collection

### ISSUE THREAD

**Issue by dimitrov-adrian** [directus/next#516]
Directus v9.0.0-beta.8
Node 12

Response:
```
{"errors":[{"message":"Invalid time value","extensions":{"code":"INTERNAL_SERVER_ERROR"}}]}
```

Console log
```
Starting with v2.0.0-beta.1 date-fns doesn't accept strings as date arguments. Please use `parseISO` to parse strings. See: https://git.io/fjule
Error
    at toDate (***/my-project/node_modules/date-fns/toDate/index.js:56:20)
    at Object.format (***/my-project/node_modules/date-fns/format/index.js:387:42)
    at PayloadService.<anonymous> (***/my-project/node_modules/directus/dist/services/payload.js:243:57)
    at Generator.next (<anonymous>)
    at fulfilled (***/my-project/node_modules/directus/dist/services/payload.js:9:58)
08:57:13 🚨 Invalid time value 
RangeError: Invalid time value
    at Object.format (***/my-project/node_modules/date-fns/format/index.js:390:11)
    at PayloadService.<anonymous> (***/my-project/node_modules/directus/dist/services/payload.js:243:57)
    at Generator.next (<anonymous>)
    at fulfilled (***/my-project/node_modules/directus/dist/services/payload.js:9:58)
08:57:13 ✨ request errored POST 500 /files 99ms


```

**Comment by maartenvn** [comment]
This is the same issue as #512 
My docker logs was not displaying the error, but my local SQLite setup does.
