### ISSUE TITLE
Installation error when remote MySQL database failed to connect

### ISSUE THREAD

**Issue by altezza04** [directus/next#609]
1. Running the `npx create-directus-project my-project` 
2. Select MySql as database & and enter remote database info
3.`(node:31698) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT
    at Connection._handleConnectTimeout (/APP/my-project/node_modules/mysql/lib/Connection.js:409:13)
    at Object.onceWrapper (events.js:420:28)
    at Socket.emit (events.js:314:20)
    at Socket._onTimeout (net.js:483:8)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:494:7)
`

**Comment by rijkvanzanten** [comment]
Sounds like a wrong credentials situation to me. If you have any more info or a accurate way to reproduce this, we'll reopen
