### ISSUE TITLE
App won't start - collection column doesn't exist

### ISSUE THREAD

**Issue by danieljwestman** [directus/next#615]
Directus 9 beta 10 
PG 12
Latest main, commit b5a92fc7 (okt 10)
Clean install/db

Can't login to the App anymore. When logging in you get:

```
directus: 16:51:30 🚨 error select "directus_collections"."collection" from "directus_collections" where "directus_collections"."id" in ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) limit $13 - column directus_collections.id does not exist 
directus: error: select "directus_collections"."collection" from "directus_collections" where "directus_collections"."id" in ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) limit $13 - column directus_collections.id does not exist
directus:     at Parser.parseErrorMessage (/Users/danielwestman/Utveckling/Directus/next/api/node_modules/pg-protocol/src/parser.ts:357:11)
directus:     at Parser.handlePacket (/Users/danielwestman/Utveckling/Directus/next/api/node_modules/pg-protocol/src/parser.ts:186:21)
directus:     at Parser.parse (/Users/danielwestman/Utveckling/Directus/next/api/node_modules/pg-protocol/src/parser.ts:101:30)
directus:     at Socket.<anonymous> (/Users/danielwestman/Utveckling/Directus/next/api/node_modules/pg-protocol/src/index.ts:7:48)
directus:     at Socket.emit (events.js:314:20)
directus:     at addChunk (_stream_readable.js:307:12)
directus:     at readableAddChunk (_stream_readable.js:282:9)
directus:     at Socket.Readable.push (_stream_readable.js:221:10)
directus:     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```
![Skärmavbild 2020-10-11 kl  16 51 53](https://user-images.githubusercontent.com/20950568/95681819-2834de80-0be2-11eb-9ea5-637b5297f581.png)

There is no column "id" on table "directus_collections"...

**Comment by danieljwestman** [comment]
New day new problem.

After fetching the latest commits (last: c8092011) I get the server running with /next `npm run setup` + `npm run dev`, doesn't get the collection error above, but everything halts. Even the login screen is not reachable. Just empty:

![Skärmavbild 2020-10-12 kl  11 19 37](https://user-images.githubusercontent.com/20950568/95729531-50255000-0c7d-11eb-9539-b180bed5a799.png)

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/next/commit/470ff1285965756d331872b273de20dbfc1eea5e
