### ISSUE TITLE
Can't login to the App - error in AST

### ISSUE THREAD

**Issue by danieljwestman** [directus/next#628]
Directus v9 - latest main, okt 13 (last commit 9e3ad304)
PG 12

New fresh install, new db

I can get to the login screen but when logging in it throws some errors and I can't get anywhere.

```
directus: 10:50:51 🚨 Cannot read property 'split' of undefined 
directus: TypeError: Cannot read property 'split' of undefined
directus:     at /Users/danielwestman/Utveckling/Directus/next/api/src/utils/get-ast-from-query.ts:127:66
directus:     at Generator.next (<anonymous>)
directus:     at fulfilled (/Users/danielwestman/Utveckling/Directus/next/api/src/utils/get-ast-from-query.ts:8:58)
directus:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
directus: 10:50:51 ✨ request errored GET 500 /users/me?fields=*,avatar.*,role.* 56ms
directus: 10:50:51 ✨ request completed POST 200 /auth/refresh 82ms
directus: 10:50:51 ✨ request completed GET 200 /settings?fields[]=*.* 89ms
directus: 10:50:51 🚨 Cannot read property 'split' of undefined 
directus: TypeError: Cannot read property 'split' of undefined
directus:     at /Users/danielwestman/Utveckling/Directus/next/api/src/utils/get-ast-from-query.ts:127:66
directus:     at Generator.next (<anonymous>)
directus:     at fulfilled (/Users/danielwestman/Utveckling/Directus/next/api/src/utils/get-ast-from-query.ts:8:58)
```

**Comment by benhaynes** [comment]
Same.
