### ISSUE TITLE
API wont start

### ISSUE THREAD

**Issue by dimitrov-adrian** [directus/next#656]
Directus: v9.0.0-beta.10 (latest from git)
Node: 12
DB: SQLite

```
directus: TypeError: Router.use() requires a middleware function but got a Object
directus:     at Function.use (/Users/e01/Downloads/next/api/node_modules/express/lib/router/index.js:458:13)
directus:     at Function.<anonymous> (/Users/e01/Downloads/next/api/node_modules/express/lib/application.js:220:21)
directus:     at Array.forEach (<anonymous>)
directus:     at Function.use (/Users/e01/Downloads/next/api/node_modules/express/lib/application.js:217:7)
directus:     at Object.<anonymous> (/Users/e01/Downloads/next/api/src/app.ts:121:5)
directus:     at Module._compile (internal/modules/cjs/loader.js:1138:30)
directus:     at Module._compile (/Users/e01/Downloads/next/api/node_modules/source-map-support/source-map-support.js:547:25)
directus:     at Module.m._compile (/private/var/folders/_c/s4kjzb_533j9f2fq1z55ch680000gn/T/ts-node-dev-hook-050683685119298216.js:57:33)
directus:     at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
directus:     at require.extensions.<computed> (/private/var/folders/_c/s4kjzb_533j9f2fq1z55ch680000gn/T/ts-node-dev-hook-050683685119298216.js:59:20)
directus: [ERROR] 00:24:01 TypeError: Router.use() requires a middleware function but got a Object
```

**Comment by rijkvanzanten** [comment]
I'd recommend removing node-modules and reinstalling them with `npm install` / `npm run setup`. I get this every now and again, seems to be a caching issue in the build chain somewhere
