### ISSUE TITLE
Changing interface does not work

### ISSUE THREAD

**Issue by dimitrov-adrian** [directus/next#682]
Changing interface of field trigger error

```
08:15:50 🚨 Sqlite does not support alter column. 
Error: Sqlite does not support alter column.
    at TableCompiler_SQLite3.addColumns (/directus/node_modules/knex/lib/dialects/sqlite3/schema/tablecompiler.js:35:11)
    at TableCompiler_SQLite3.TableCompiler.alterColumns (/directus/node_modules/knex/lib/schema/tablecompiler.js:184:10)
    at TableCompiler_SQLite3.TableCompiler.alter (/directus/node_modules/knex/lib/schema/tablecompiler.js:77:8)
    at TableCompiler_SQLite3.TableCompiler.toSQL (/directus/node_modules/knex/lib/schema/tablecompiler.js:34:20)
    at TableBuilder.toSQL (/directus/node_modules/knex/lib/schema/tablebuilder.js:45:42)
    at SchemaCompiler_SQLite3.alterTable (/directus/node_modules/knex/lib/schema/compiler.js:89:25)
    at SchemaCompiler_SQLite3.toSQL (/directus/node_modules/knex/lib/schema/compiler.js:72:26)
    at SchemaBuilder.toSQL (/directus/node_modules/knex/lib/schema/builder.js:79:43)
    at /directus/node_modules/knex/lib/runner.js:31:36
    at /directus/node_modules/knex/lib/runner.js:277:24
08:15:50 ✨ request errored PATCH 500 /fields/table1/body 18ms
```

---

### Project details
Directus Version: 9.0.0-beta.13
Environment: production
OS: Linux 4.19.76-linuxkit
Node: 14.13.1

**Comment by dimitrov-adrian** [comment]
Also appears on changing display and for any field change.

```
directus: 09:10:20 🚨 Sqlite does not support alter column. 
directus: Error: Sqlite does not support alter column.
directus:     at TableCompiler_SQLite3.addColumns (/Users/e01/Downloads/next/api/node_modules/knex/lib/dialects/sqlite3/schema/tablecompiler.js:35:11)
directus:     at TableCompiler_SQLite3.TableCompiler.alterColumns (/Users/e01/Downloads/next/api/node_modules/knex/lib/schema/tablecompiler.js:184:10)
directus:     at TableCompiler_SQLite3.TableCompiler.alter (/Users/e01/Downloads/next/api/node_modules/knex/lib/schema/tablecompiler.js:77:8)
directus:     at TableCompiler_SQLite3.TableCompiler.toSQL (/Users/e01/Downloads/next/api/node_modules/knex/lib/schema/tablecompiler.js:34:20)
directus:     at TableBuilder.toSQL (/Users/e01/Downloads/next/api/node_modules/knex/lib/schema/tablebuilder.js:45:42)
directus:     at SchemaCompiler_SQLite3.alterTable (/Users/e01/Downloads/next/api/node_modules/knex/lib/schema/compiler.js:89:25)
directus:     at SchemaCompiler_SQLite3.toSQL (/Users/e01/Downloads/next/api/node_modules/knex/lib/schema/compiler.js:72:26)
directus:     at SchemaBuilder.toSQL (/Users/e01/Downloads/next/api/node_modules/knex/lib/schema/builder.js:79:43)
directus:     at /Users/e01/Downloads/next/api/node_modules/knex/lib/runner.js:31:36
directus:     at /Users/e01/Downloads/next/api/node_modules/knex/lib/runner.js:277:2
```
