### ISSUE TITLE
Install breaks using SQLite

### ISSUE THREAD

**Issue by Kinzi** [directus/next#802]
npx and yarn installation breaks for me chosing SQLite:

```
? Choose your database client SQLite (Beta)
? Database File Path: /Users/ME/Code/directus/data.db
Knex: run
$ npm install sqlite3 --save
Cannot find module 'sqlite3'
```

**Comment by Kinzi** [comment]
FYI: was able to get around by cd into project, run `npm install sqlite3 --save`and then `npx directus init`

**Comment by rijkvanzanten** [comment]
@Kinzi Did you happen to have `sqlite3` installed globally, or somewhere up the tree? 

The CLI tries requiring the package using the same methods as the DB package:

https://github.com/directus/next/blob/6b345193c120ec058e9c154afd4fc37a483e55f0/api/src/cli/commands/init/index.ts#L31-L37

Which seems to work as expected on my end 🤔 (just tried on a fresh install using `npx create-directus-project`

**Comment by Kinzi** [comment]
hmm. i checked but I it's not installed globally. Just tried with a different node version (10 and 14). Same result. Here is the full stack trace:

```
? Database File Path: /Users/seb/Code/my-project/data.db
Knex: run
$ npm install sqlite3 --save
Cannot find module 'sqlite3'
Require stack:
- /Users/seb/Code/my-project/node_modules/knex/lib/dialects/sqlite3/index.js
- /Users/seb/Code/my-project/node_modules/knex/lib/knex.js
- /Users/seb/Code/my-project/node_modules/knex/lib/index.js
- /Users/seb/Code/my-project/node_modules/knex/knex.js
- /Users/seb/Code/my-project/node_modules/directus/dist/cli/utils/create-db-connection.js
- /Users/seb/Code/my-project/node_modules/directus/dist/cli/commands/init/index.js
- /Users/seb/Code/my-project/node_modules/directus/dist/cli/index.js
- /Users/seb/Code/my-project/node_modules/directus/cli.js
Error: Cannot find module 'sqlite3'
Require stack:
- /Users/seb/Code/my-project/node_modules/knex/lib/dialects/sqlite3/index.js
- /Users/seb/Code/my-project/node_modules/knex/lib/knex.js
- /Users/seb/Code/my-project/node_modules/knex/lib/index.js
- /Users/seb/Code/my-project/node_modules/knex/knex.js
- /Users/seb/Code/my-project/node_modules/directus/dist/cli/utils/create-db-connection.js
- /Users/seb/Code/my-project/node_modules/directus/dist/cli/commands/init/index.js
- /Users/seb/Code/my-project/node_modules/directus/dist/cli/index.js
- /Users/seb/Code/my-project/node_modules/directus/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Client_SQLite3._driver (/Users/seb/Code/my-project/node_modules/knex/lib/dialects/sqlite3/index.js:35:12)
    at Client_SQLite3.initializeDriver (/Users/seb/Code/my-project/node_modules/knex/lib/client.js:231:26)
    at Client_SQLite3.Client (/Users/seb/Code/my-project/node_modules/knex/lib/client.js:69:10)
    at new Client_SQLite3 (/Users/seb/Code/my-project/node_modules/knex/lib/dialects/sqlite3/index.js:17:10)
    at Object.Knex [as default] (/Users/seb/Code/my-project/node_modules/knex/lib/knex.js:53:28)
    at Object.createDBConnection [as default] (/Users/seb/Code/my-project/node_modules/directus/dist/cli/utils/create-db-connection.js:50:30)
(node:46767) UnhandledPromiseRejectionWarning: Error: Knex: run
$ npm install sqlite3 --save
Cannot find module 'sqlite3'
Require stack:
- /Users/seb/Code/my-project/node_modules/knex/lib/dialects/sqlite3/index.js
- /Users/seb/Code/my-project/node_modules/knex/lib/knex.js
- /Users/seb/Code/my-project/node_modules/knex/lib/index.js
- /Users/seb/Code/my-project/node_modules/knex/knex.js
- /Users/seb/Code/my-project/node_modules/directus/dist/cli/utils/create-db-connection.js
- /Users/seb/Code/my-project/node_modules/directus/dist/cli/commands/init/index.js
- /Users/seb/Code/my-project/node_modules/directus/dist/cli/index.js
- /Users/seb/Code/my-project/node_modules/directus/cli.js
    at Client_SQLite3.initializeDriver (/Users/seb/Code/my-project/node_modules/knex/lib/client.js:235:13)
    at Client_SQLite3.Client (/Users/seb/Code/my-project/node_modules/knex/lib/client.js:69:10)
    at new Client_SQLite3 (/Users/seb/Code/my-project/node_modules/knex/lib/dialects/sqlite3/index.js:17:10)
    at Object.Knex [as default] (/Users/seb/Code/my-project/node_modules/knex/lib/knex.js:53:28)
    at Object.createDBConnection [as default] (/Users/seb/Code/my-project/node_modules/directus/dist/cli/utils/create-db-connection.js:50:30)
    at /Users/seb/Code/my-project/node_modules/directus/dist/cli/commands/init/index.js:51:58
    at Generator.next (<anonymous>)
    at fulfilled (/Users/seb/Code/my-project/node_modules/directus/dist/cli/commands/init/index.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:46767) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:46767) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by rijkvanzanten** [comment]
Hmm, this'll be tricky to fix without being able to reproduce :/ @benhaynes could you give it a shot?

This is the expected result:

![CleanShot 2020-10-29 at 11 07 59](https://user-images.githubusercontent.com/9141017/97592501-1a9b9900-19d7-11eb-9bce-9e25d3d27e54.png)

**Comment by benhaynes** [comment]
Samsies...

```
Ben@mac-mini Sites % npx create-directus-project directus-test
npx: installed 53 in 4.21s
? Choose your database client SQLite (Beta)
? Database File Path: /Users/Ben/Sites/directus-test/data.db
Knex: run
$ npm install sqlite3 --save
Cannot find module 'sqlite3'
Require stack:
- /Users/Ben/Sites/directus-test/node_modules/knex/lib/dialects/sqlite3/index.js
- /Users/Ben/Sites/directus-test/node_modules/knex/lib/knex.js
- /Users/Ben/Sites/directus-test/node_modules/knex/lib/index.js
- /Users/Ben/Sites/directus-test/node_modules/knex/knex.js
- /Users/Ben/Sites/directus-test/node_modules/directus/dist/cli/utils/create-db-connection.js
- /Users/Ben/Sites/directus-test/node_modules/directus/dist/cli/commands/init/index.js
- /Users/Ben/Sites/directus-test/node_modules/directus/dist/cli/index.js
- /Users/Ben/Sites/directus-test/node_modules/directus/cli.js
Error: Cannot find module 'sqlite3'
Require stack:
- /Users/Ben/Sites/directus-test/node_modules/knex/lib/dialects/sqlite3/index.js
- /Users/Ben/Sites/directus-test/node_modules/knex/lib/knex.js
- /Users/Ben/Sites/directus-test/node_modules/knex/lib/index.js
- /Users/Ben/Sites/directus-test/node_modules/knex/knex.js
- /Users/Ben/Sites/directus-test/node_modules/directus/dist/cli/utils/create-db-connection.js
- /Users/Ben/Sites/directus-test/node_modules/directus/dist/cli/commands/init/index.js
- /Users/Ben/Sites/directus-test/node_modules/directus/dist/cli/index.js
- /Users/Ben/Sites/directus-test/node_modules/directus/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1065:15)
    at Function.Module._load (internal/modules/cjs/loader.js:911:27)
    at Module.require (internal/modules/cjs/loader.js:1125:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Client_SQLite3._driver (/Users/Ben/Sites/directus-test/node_modules/knex/lib/dialects/sqlite3/index.js:35:12)
    at Client_SQLite3.initializeDriver (/Users/Ben/Sites/directus-test/node_modules/knex/lib/client.js:231:26)
    at Client_SQLite3.Client (/Users/Ben/Sites/directus-test/node_modules/knex/lib/client.js:69:10)
    at new Client_SQLite3 (/Users/Ben/Sites/directus-test/node_modules/knex/lib/dialects/sqlite3/index.js:17:10)
    at Object.Knex [as default] (/Users/Ben/Sites/directus-test/node_modules/knex/lib/knex.js:53:28)
    at Object.createDBConnection [as default] (/Users/Ben/Sites/directus-test/node_modules/directus/dist/cli/utils/create-db-connection.js:50:30)
(node:38734) UnhandledPromiseRejectionWarning: Error: Knex: run
$ npm install sqlite3 --save
Cannot find module 'sqlite3'
Require stack:
- /Users/Ben/Sites/directus-test/node_modules/knex/lib/dialects/sqlite3/index.js
- /Users/Ben/Sites/directus-test/node_modules/knex/lib/knex.js
- /Users/Ben/Sites/directus-test/node_modules/knex/lib/index.js
- /Users/Ben/Sites/directus-test/node_modules/knex/knex.js
- /Users/Ben/Sites/directus-test/node_modules/directus/dist/cli/utils/create-db-connection.js
- /Users/Ben/Sites/directus-test/node_modules/directus/dist/cli/commands/init/index.js
- /Users/Ben/Sites/directus-test/node_modules/directus/dist/cli/index.js
- /Users/Ben/Sites/directus-test/node_modules/directus/cli.js
    at Client_SQLite3.initializeDriver (/Users/Ben/Sites/directus-test/node_modules/knex/lib/client.js:235:13)
    at Client_SQLite3.Client (/Users/Ben/Sites/directus-test/node_modules/knex/lib/client.js:69:10)
    at new Client_SQLite3 (/Users/Ben/Sites/directus-test/node_modules/knex/lib/dialects/sqlite3/index.js:17:10)
    at Object.Knex [as default] (/Users/Ben/Sites/directus-test/node_modules/knex/lib/knex.js:53:28)
    at Object.createDBConnection [as default] (/Users/Ben/Sites/directus-test/node_modules/directus/dist/cli/utils/create-db-connection.js:50:30)
    at /Users/Ben/Sites/directus-test/node_modules/directus/dist/cli/commands/init/index.js:51:58
    at Generator.next (<anonymous>)
    at fulfilled (/Users/Ben/Sites/directus-test/node_modules/directus/dist/cli/commands/init/index.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:38734) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:38734) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Ben@mac-mini Sites % 
```
