### ISSUE TITLE
Can't create (admin) role on fresh instance

### ISSUE THREAD

**Issue by MiniDigger** [directus/next#807]
Running RC3 using Docker and a Postgres db.

The install script successfully created my tables and filled some of them, but creating an admin role failed.
https://github.com/directus/next/blob/6b345193c120ec058e9c154afd4fc37a483e55f0/.github/actions/build-images/rootfs/directus/images/main/rootfs/usr/bin/entrypoint#L17

Even if I run that command on cli it fails with the same error
```
/directus $ npx -n="--trace-warnings" directus roles create --name Administrator --admin 
(node:1094) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'column_name' of undefined
    at Postgres.<anonymous> (/directus/node_modules/knex-schema-inspector/dist/dialects/postgres.js:325:51)
    at step (/directus/node_modules/knex-schema-inspector/dist/dialects/postgres.js:33:23)
    at Object.next (/directus/node_modules/knex-schema-inspector/dist/dialects/postgres.js:14:53)
    at fulfilled (/directus/node_modules/knex-schema-inspector/dist/dialects/postgres.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
(node:1094) TypeError: Cannot read property 'column_name' of undefined
    at Postgres.<anonymous> (/directus/node_modules/knex-schema-inspector/dist/dialects/postgres.js:325:51)
    at step (/directus/node_modules/knex-schema-inspector/dist/dialects/postgres.js:33:23)
    at Object.next (/directus/node_modules/knex-schema-inspector/dist/dialects/postgres.js:14:53)
    at fulfilled (/directus/node_modules/knex-schema-inspector/dist/dialects/postgres.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1094) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
^C
```

this also happens with a non standard non admin role
```/directus $ npx directus roles create --name Test
(node:1262) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'column_name' of undefined
    at Postgres.<anonymous> (/directus/node_modules/knex-schema-inspector/dist/dialects/postgres.js:325:51)
    at step (/directus/node_modules/knex-schema-inspector/dist/dialects/postgres.js:33:23)
    at Object.next (/directus/node_modules/knex-schema-inspector/dist/dialects/postgres.js:14:53)
    at fulfilled (/directus/node_modules/knex-schema-inspector/dist/dialects/postgres.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1262) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1262) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^C```

**Comment by rijkvanzanten** [comment]
This seems to be a problem in `knex-schema-inspector`: https://github.com/knex/knex-schema-inspector

Mind opening this issue over there?

**Comment by MiniDigger** [comment]
this happens for create user too (after I manually created the role)
