### ISSUE TITLE
Issue with Redis RateLimiter

### ISSUE THREAD

**Issue by botzill** [directus/next#835]
I get this error when I use RateLimiter with redis:

```
08:42:23 🚨 this.client.multi is not a function 
TypeError: this.client.multi is not a function
    at /directus/node_modules/rate-limiter-flexible/lib/RateLimiterRedis.js:60:33
    at new Promise (<anonymous>)
    at RateLimiterRedis._upsert (/directus/node_modules/rate-limiter-flexible/lib/RateLimiterRedis.js:58:12)
    at /directus/node_modules/rate-limiter-flexible/lib/RateLimiterStoreAbstract.js:203:12
    at new Promise (<anonymous>)
    at RateLimiterRedis.consume (/directus/node_modules/rate-limiter-flexible/lib/RateLimiterStoreAbstract.js:195:12)
    at /directus/node_modules/directus/dist/middleware/rate-limiter.js:28:31
    at Generator.next (<anonymous>)
    at /directus/node_modules/directus/dist/middleware/rate-limiter.js:8:71
    at new Promise (<anonymous>)
```

**Comment by rijkvanzanten** [comment]
@botzill What configuration are you using for Redis?

This looks like an issue in `rate-limiter-flexible` and/or a configuration problem 🤔

**Comment by botzill** [comment]
I do set `REDIS` env with uri to redis instance.
