### ISSUE TITLE
Error when building @Directus/app in @vue/cli-shared-utils

### ISSUE THREAD

**Issue by danieljwestman** [directus/next#882]
v9.0.0-rc.6
PG 12
Latest commit [3a54e396b8831112e74013bc1937e9d4995f03cd](https://github.com/directus/next/commit/3a54e396b8831112e74013bc1937e9d4995f03cd)
Clean install

When running `npm run setup` it throws an error on building the app:

```
lerna ERR! npm run build exited 1 in '@Directus/app'
lerna ERR! npm run build stdout:

> @directus/app@9.0.0-rc.6 build /directus/app
> vue-cli-service build


lerna ERR! npm run build stderr:
//directus/app/node_modules/@vue/cli-shared-utils/node_modules/chalk/index.js:72
ansiStyles.color.closeRe = new RegExp(escapeStringRegexp(ansiStyles.color.close), 'g');

TypeError: Cannot read property 'close' of undefined
```

**Comment by rijkvanzanten** [comment]
This seems to be a problem / version conflict in `chalk` / `ansi-styles` / `@vue/cli-shared-utils`. 

`ansi-styles` isn't a direct dependency of Directus, so this should be fixed under either `@vue/cli-shared-utils` or `chalk` 🤔 

That being said, I'll hard-install a specific version of `ansi-styles` to get around this issue for now

**Comment by rijkvanzanten** [comment]
@danieljwestman I got rid of the `npm run setup` command. After fixing the module resolution from the root, you should be able to "just" run `npm install` from the root, and `npm run dev` from the root respectively.

**Comment by danieljwestman** [comment]
Great!

**Comment by danieljwestman** [comment]
Nope... Not working...

```
DWs-MacBook:app danielwestman$ npm run dev

> directus-monorepo@ dev /Users/danielwestman/Utveckling/Grannskap/app
> lerna run dev --stream --parallel

lerna notice cli v3.22.1
lerna info Executing command in 4 packages: "npm run dev"
directus: > directus@10.1.0 dev /Users/danielwestman/Utveckling/Grannskap/app/api
directus: > cross-env NODE_ENV=development LOG_LEVEL=trace ts-node-dev --files src/start.ts --respawn --watch "src/**/*.ts" --transpile-only
@directus/app: > @directus/app@10.1.0 dev /Users/danielwestman/Utveckling/Grannskap/app/app
@directus/app: > vue-cli-service serve
@directus/docs: > @directus/docs@10.1.0 dev /Users/danielwestman/Utveckling/Grannskap/app/docs
@directus/docs: > npm-watch build
@directus/specs: > @directus/specs@10.1.0 dev /Users/danielwestman/Utveckling/Grannskap/app/packages/spec
@directus/specs: > npm-watch build
@directus/app: /Users/danielwestman/Utveckling/Grannskap/app/app/node_modules/@vue/cli-shared-utils/node_modules/chalk/index.js:72
@directus/app: ansiStyles.color.closeRe = new RegExp(escapeStringRegexp(ansiStyles.color.close), 'g');
@directus/app:                                                                           ^
@directus/app: TypeError: Cannot read property 'close' of undefined
@directus/app:     at Object.<anonymous> (/Users/danielwestman/Utveckling/Grannskap/app/app/node_modules/@vue/cli-shared-utils/node_modules/chalk/index.js:72:75)
@directus/app:     at Module._compile (internal/modules/cjs/loader.js:1076:30)
@directus/app:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
@directus/app:     at Module.load (internal/modules/cjs/loader.js:941:32)
@directus/app:     at Function.Module._load (internal/modules/cjs/loader.js:782:14)
@directus/app:     at Module.require (internal/modules/cjs/loader.js:965:19)
@directus/app:     at require (internal/modules/cjs/helpers.js:88:18)
@directus/app:     at Object.<anonymous> (/Users/danielwestman/Utveckling/Grannskap/app/app/node_modules/@vue/cli-shared-utils/lib/logger.js:1:15)
@directus/app:     at Module._compile (internal/modules/cjs/loader.js:1076:30)
@directus/app:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
@directus/app: npm ERR! code ELIFECYCLE
@directus/app: npm ERR! errno 1
@directus/app: npm ERR! @directus/app@10.1.0 dev: `vue-cli-service serve`
@directus/app: npm ERR! Exit status 1
@directus/app: npm ERR! 
@directus/app: npm ERR! Failed at the @directus/app@10.1.0 dev script.
@directus/app: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
@directus/app: npm ERR! A complete log of this run can be found in:
@directus/app: npm ERR!     /Users/danielwestman/.npm/_logs/2020-11-05T19_10_14_138Z-debug.log
lerna ERR! npm run dev exited 1 in '@directus/app'

```

**Comment by rijkvanzanten** [comment]
Make sure to fully clear all node_module folders and reset any changes in package-locks if you have any before re-installing all the dependencies

**Comment by danieljwestman** [comment]
Why remove the setup command, it made all the work...

**Comment by rijkvanzanten** [comment]
Because it would install every package individually, causing conflicts in package versions. Wouldn't resolve devdependencies properly, causing build problems, etc etc

**Comment by danieljwestman** [comment]
Okay. I'll buy that.

I removed all node_modules and lock files. Run `npm install` in root and then `npm run dev`.

New errors:

```
DWs-MacBook:app danielwestman$ npm run dev

> directus-monorepo@ dev /Users/danielwestman/Utveckling/Grannskap/app
> lerna run dev --stream --parallel

lerna notice cli v3.22.1
lerna info Executing command in 4 packages: "npm run dev"
directus: > directus@10.1.0 dev /Users/danielwestman/Utveckling/Grannskap/app/api
directus: > cross-env NODE_ENV=development LOG_LEVEL=trace ts-node-dev --files src/start.ts --respawn --watch "src/**/*.ts" --transpile-only
@directus/app: > @directus/app@10.1.0 dev /Users/danielwestman/Utveckling/Grannskap/app/app
@directus/app: > vue-cli-service serve
@directus/docs: > @directus/docs@10.1.0 dev /Users/danielwestman/Utveckling/Grannskap/app/docs
@directus/docs: > npm-watch build
@directus/specs: > @directus/specs@10.1.0 dev /Users/danielwestman/Utveckling/Grannskap/app/packages/spec
@directus/specs: > npm-watch build
directus: [INFO] 20:24:05 ts-node-dev ver. 1.0.0 (using ts-node ver. 9.0.0, typescript ver. 3.9.7)
@directus/app:  INFO  Starting development server...
@directus/docs: Building docs...
@directus/docs: Built docs in 384 ms
@directus/specs: Created dist/openapi.json from specs/openapi.yaml
@directus/app: Starting type checking service...
@directus/app: Using 1 worker with 2048MB memory limit
directus: Compilation error in /Users/danielwestman/Utveckling/Grannskap/app/api/src/services/specifications.ts
directus: (node:7293) UnhandledPromiseRejectionWarning: Error: ⨯ Unable to compile TypeScript:
directus: src/services/specifications.ts(12,25): error TS2307: Cannot find module '@directus/format-title' or its corresponding type declarations.
directus:     at Object.<anonymous> (/Users/danielwestman/Utveckling/Grannskap/app/api/src/services/specifications.ts:1:7)
directus:     at Module._compile (internal/modules/cjs/loader.js:1076:30)
directus:     at Module._compile (/Users/danielwestman/Utveckling/Grannskap/app/node_modules/source-map-support/source-map-support.js:547:25)
directus:     at Module.m._compile (/private/var/folders/dh/7ffkf9rn43n1rhxhq5pwvndm0000gn/T/ts-node-dev-hook-9166262435611383.js:57:33)
directus:     at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
directus:     at require.extensions.<computed> (/private/var/folders/dh/7ffkf9rn43n1rhxhq5pwvndm0000gn/T/ts-node-dev-hook-9166262435611383.js:59:20)
directus:     at Object.nodeDevHook [as .ts] (/Users/danielwestman/Utveckling/Grannskap/app/node_modules/ts-node-dev/lib/hook.js:63:13)
directus:     at Module.load (internal/modules/cjs/loader.js:941:32)
directus:     at Function.Module._load (internal/modules/cjs/loader.js:782:14)
directus:     at Module.require (internal/modules/cjs/loader.js:965:19)
directus: (Use `node --trace-warnings ...` to show where the warning was created)
directus: (node:7293) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
directus: (node:7293) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
@directus/app:  ERROR  Failed to compile with 8 errors20:24:44
@directus/app: This dependency was not found:
@directus/app: * @directus/format-title in ../node_modules/cache-loader/dist/cjs.js??ref--13-0!../node_modules/babel-loader/lib!../node_modules/ts-loader??ref--13-2!../node_modules/cache-loader/dist/cjs.js??ref--0-0!../node_modules/vue-loader/lib??vue-loader-options!./src/components/v-field-template/field-list-item.vue?vue&type=script&lang=ts&, ../node_modules/cache-loader/dist/cjs.js??ref--13-0!../node_modules/babel-loader/lib!../node_modules/ts-loader??ref--13-2!../node_modules/cache-loader/dist/cjs.js??ref--0-0!../node_modules/vue-loader/lib??vue-loader-options!./src/displays/formatted-value/formatted-value.vue?vue&type=script&lang=ts& and 6 others
@directus/app: To install it, you can run: npm install --save @directus/format-title
@directus/app: ERROR in /Users/danielwestman/Utveckling/Grannskap/app/app/src/components/v-field-template/field-list-item.vue(25,25):
@directus/app: 25:25 Cannot find module '@directus/format-title' or its corresponding type declarations.
@directus/app:     23 | import { defineComponent, PropType } from '@vue/composition-api';
@directus/app:     24 | import { FieldTree } from './types';
@directus/app:   > 25 | import formatTitle from '@directus/format-title';
@directus/app:        |                         ^
@directus/app:     26 | 
@directus/app:     27 | export default defineComponent({
@directus/app:     28 | 	name: 'field-list-item',
@directus/app: ERROR in /Users/danielwestman/Utveckling/Grannskap/app/app/src/displays/color/color.vue(10,25):
@directus/app: 10:25 Cannot find module '@directus/format-title' or its corresponding type declarations.
@directus/app:      8 | <script lang="ts">
@directus/app:      9 | import { defineComponent, computed, PropType } from '@vue/composition-api';
@directus/app:   > 10 | import formatTitle from '@directus/format-title';
@directus/app:        |                         ^
@directus/app:     11 | import Color from 'color';
@directus/app:     12 | import { isHex } from '@/utils/color';
@directus/app:     13 | 
@directus/app: ERROR in /Users/danielwestman/Utveckling/Grannskap/app/app/src/displays/formatted-value/formatted-value.vue(11,25):
@directus/app: 11:25 Cannot find module '@directus/format-title' or its corresponding type declarations.
@directus/app:      9 | <script lang="ts">
@directus/app:     10 | import { defineComponent, computed } from '@vue/composition-api';
@directus/app:   > 11 | import formatTitle from '@directus/format-title';
@directus/app:        |                         ^
@directus/app:     12 | 
@directus/app:     13 | export default defineComponent({
@directus/app:     14 | 	props: {
@directus/app: ERROR in /Users/danielwestman/Utveckling/Grannskap/app/app/src/displays/labels/labels.vue(32,25):
@directus/app: 32:25 Cannot find module '@directus/format-title' or its corresponding type declarations.
@directus/app:     30 | <script lang="ts">
@directus/app:     31 | import { defineComponent, computed, PropType } from '@vue/composition-api';
@directus/app:   > 32 | import formatTitle from '@directus/format-title';
@directus/app:        |                         ^
@directus/app:     33 | 
@directus/app:     34 | type Choice = {
@directus/app:     35 | 	value: string;
@directus/app: ERROR in /Users/danielwestman/Utveckling/Grannskap/app/app/src/interfaces/code/code.vue(28,25):
@directus/app: 28:25 Cannot find module '@directus/format-title' or its corresponding type declarations.
@directus/app:     26 | import 'codemirror/keymap/sublime.js';
@directus/app:     27 | 
@directus/app:   > 28 | import formatTitle from '@directus/format-title';
@directus/app:        |                         ^
@directus/app:     29 | 
@directus/app:     30 | export default defineComponent({
@directus/app:     31 | 	props: {
@directus/app: ERROR in /Users/danielwestman/Utveckling/Grannskap/app/app/src/interfaces/icon/icon.vue(51,25):
@directus/app: 51:25 Cannot find module '@directus/format-title' or its corresponding type declarations.
@directus/app:     49 | import icons from './icons.json';
@directus/app:     50 | import { defineComponent, ref, computed } from '@vue/composition-api';
@directus/app:   > 51 | import formatTitle from '@directus/format-title';
@directus/app:        |                         ^
@directus/app:     52 | 
@directus/app:     53 | export default defineComponent({
@directus/app:     54 | 	props: {
@directus/app: ERROR in /Users/danielwestman/Utveckling/Grannskap/app/app/src/interfaces/tags/tags.vue(46,25):
@directus/app: 46:25 Cannot find module '@directus/format-title' or its corresponding type declarations.
@directus/app:     44 | <script lang="ts">
@directus/app:     45 | import { defineComponent, PropType, ref, computed, watch } from '@vue/composition-api';
@directus/app:   > 46 | import formatTitle from '@directus/format-title';
@directus/app:        |                         ^
@directus/app:     47 | 
@directus/app:     48 | export default defineComponent({
@directus/app:     49 | 	props: {
@directus/app: ERROR in /Users/danielwestman/Utveckling/Grannskap/app/app/src/stores/collections.ts(7,25):
@directus/app: 7:25 Cannot find module '@directus/format-title' or its corresponding type declarations.
@directus/app:      5 | import { notEmpty } from '@/utils/is-empty/';
@directus/app:      6 | import VueI18n from 'vue-i18n';
@directus/app:   >  7 | import formatTitle from '@directus/format-title';
@directus/app:        |                         ^
@directus/app:      8 | import notify from '@/utils/notify';
@directus/app:      9 | 
@directus/app:     10 | export const useCollectionsStore = createStore({
@directus/app: ERROR in /Users/danielwestman/Utveckling/Grannskap/app/app/src/stores/fields.ts(6,25):
@directus/app: 6:25 Cannot find module '@directus/format-title' or its corresponding type declarations.
@directus/app:     4 | import { notEmpty } from '@/utils/is-empty/';
@directus/app:     5 | import { i18n } from '@/lang';
@directus/app:   > 6 | import formatTitle from '@directus/format-title';
@directus/app:       |                         ^
@directus/app:     7 | import { useRelationsStore } from '@/stores/';
@directus/app:     8 | import { Relation, FieldRaw, Field } from '@/types';
@directus/app:     9 | import { merge } from 'lodash';
@directus/app: Version: typescript 3.9.7
@directus/app: Time: 25551ms
```

**Comment by Fusseldieb** [comment]
@danieljwestman Try cloning from the repo again (clean, please). I had similar issues and rijk fixed them. This might work for you too.
