### ISSUE TITLE
Error trying to migrate tables from v8 to v9

### ISSUE THREAD

**Issue by tuxnese** [directus/next#888]
I am not sure that what I have tried is expected to work.
I have copied a table from a directus v8 to a fresh directus v9.
Here is the dump of the v9 database ( except the users table )
[directus_v9_dump.sql.zip](https://github.com/directus/next/files/5494980/directus_v9_dump.sql.zip)

When I try to open the collection I get on the server

15:15:55 🚨 Cannot read property 'Column_name' of undefined 
TypeError: Cannot read property 'Column_name' of undefined
    at MySQL.<anonymous> (/var/www/directus_v9/node_modules/knex-schema-inspector/dist/dialects/mysql.js:275:60)
    at step (/var/www/directus_v9/node_modules/knex-schema-inspector/dist/dialects/mysql.js:33:23)
    at Object.next (/var/www/directus_v9/node_modules/knex-schema-inspector/dist/dialects/mysql.js:14:53)
    at fulfilled (/var/www/directus_v9/node_modules/knex-schema-inspector/dist/dialects/mysql.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by rijkvanzanten** [comment]
This is a problem in `knex-schema-inspector`. I'll move this issue over to that repo

**Comment by rijkvanzanten** [comment]
Ref https://github.com/knex/knex-schema-inspector/issues/27
