### ISSUE TITLE
Cannot access or upload files on S3 bucket

### ISSUE THREAD

**Issue by flayks** [directus/next#895]
I installed my Directus `v9-rc6` instance on my Docker server (using docker-compose) and added my bucket informations to host uploads on a S3-compatible bucket (Backblaze B2 in this case) but I run into errors. It worked seamlessly with the v8 with the same bucket provider. Did anything change with the v9?

Here is the config:
```docker
version: "3"
services:
  directus:
    container_name: site-apidev
    image: directus/next:v9-rc.6
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      VIRTUAL_PORT: 8085
      VIRTUAL_HOST: api-dev.site.com
      LETSENCRYPT_HOST: api-dev.site.com
      LETSENCRYPT_EMAIL: contact@site.com
    networks:
      - reverse-proxy
      - db-mysql

networks:
  db-mysql:
    external: true
  reverse-proxy:
    external: true
```

I then uploaded my files into the bucket and added the config on the .env file:

```env
####################################################################################################
## File Storage

# Local
# STORAGE_LOCAL_DRIVER=local
# STORAGE_LOCAL_ROOT=./uploads

STORAGE_LOCATIONS=BACKBLAZE
STORAGE_BACKBLAZE_DRIVER=s3
STORAGE_BACKBLAZE_KEY=xxx
STORAGE_BACKBLAZE_SECRET=xxx
STORAGE_BACKBLAZE_BUCKET=site-api
STORAGE_BACKBLAZE_REGION=eu-central-003
STORAGE_BACKBLAZE_ENDPOINT=https://s3.eu-central-003.backblazeb2.com
STORAGE_BACKBLAZE_PUBLIC_URL=https://cdn.site.com/file/site-api/
```

And the error I get from the logs:

`11:13:36 :rotating_light: E_INVALID_CONFIG: Make sure to define config for local disk`

and the browser when accessing a `https://site.com/assets/xxx`:

`{"errors":[{"message":"E_INVALID_CONFIG: Make sure to define config for local disk","extensions":{"code":"INTERNAL_SERVER_ERROR"}}]}`

Is there an issue here on my side? Why does it say "Make sure to define config for local disk"?

**Comment by rijkvanzanten** [comment]
It should use the first item in `STORAGE_LOCATIONS` as the default driver, but it seems like it's accidentally still trying to use `local` somewhere 🤔

**Comment by botzill** [comment]
For me works to upload to S3

**Comment by flayks** [comment]
> For me works to upload to S3

Could you please share me your config? maybe I'm doing something weird on my side idk haha

**Comment by botzill** [comment]
Here are my envs:

```
STORAGE_LOCATIONS: s3
STORAGE_S3_BUCKET: bucs
STORAGE_S3_DRIVER: s3
STORAGE_S3_ENDPOINT: https://ams3.digitaloceanspaces.com
STORAGE_S3_KEY: my_key
STORAGE_S3_PUBLIC_URL: https://my.ams3.digitaloceanspaces.com
STORAGE_S3_REGION: ams3
STORAGE_S3_SECRET: my_sec
```

Works OK on DigitalOcean.

**Comment by flayks** [comment]
Definitely weird then… I updated my config following yours, but no luck.

The log errors:

```
 10:00:47 🚨 E_INVALID_CONFIG: Make sure to define config for local disk
 InvalidConfig: E_INVALID_CONFIG: Make sure to define config for local disk
     at Function.missingDiskConfig (/directus/node_modules/@slynova/flydrive/build/exceptions/InvalidConfig.js:16:16)
     at StorageManager.disk (/directus/node_modules/@slynova/flydrive/build/StorageManager.js:57:46)
     at /directus/node_modules/directus/dist/controllers/assets.js:47:48
     at Generator.next (<anonymous>)
     at fulfilled (/directus/node_modules/directus/dist/controllers/assets.js:5:58)
     at processTicksAndRejections (internal/process/task_queues.js:93:5)
 10:00:47 ✨ request errored GET 500 /assets/f22b2a76-ba89-4f86-b968-b0bc5d8bbffe?key=system-medium-cover&modified=2020-10-30T20:54:39Z&access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU2MGM4MWRjLTE2NWEtNDc5MC1iY2VhLTBhNjM1MTdhYzhjMyIsImlhdCI6MTYwNDY1Njg0NiwiZXhwIjoxNjA0NjU3NzQ2fQ.IrP2UGbgmMST-_ZKo9is4MVFLOjBCPxbVLMkx2UBjsU 51ms
```

**Comment by rijkvanzanten** [comment]
@flayks I just tried it on a fresh install (rc12) with the following config:

![CleanShot 2020-11-11 at 14 02 18](https://user-images.githubusercontent.com/9141017/98853056-90b3ed00-2426-11eb-842c-4f44459ba0ac.png)

and I'm not seeing your issue.. Could you try updating to the latest version of Directus and check if you're still running into this issue?

**Comment by flayks** [comment]
Sorry for the delay @rijkvanzanten. Upgraded the Docker instance of Directus to rc9-14, still having the same issue unfortunately.

```env
####################################################################################################
## File Storage

STORAGE_LOCATIONS=backblaze

# S3 bucket
STORAGE_BACKBLAZE_DRIVER=s3
STORAGE_BACKBLAZE_KEY=xxx
STORAGE_BACKBLAZE_SECRET=xxx
STORAGE_BACKBLAZE_BUCKET=bucketname
STORAGE_BACKBLAZE_REGION=eu-central-003
STORAGE_BACKBLAZE_ENDPOINT=s3.eu-central-003.backblazeb2.com
STORAGE_BACKBLAZE_ROOT=/
STORAGE_BACKBLAZE_PUBLIC_URL=https://cdn.site.com/file/bucketname/
```

```
20:33:57 🚨 E_INVALID_CONFIG: Make sure to define config for local disk
 InvalidConfig: E_INVALID_CONFIG: Make sure to define config for local disk
     at Function.missingDiskConfig (/directus/node_modules/@slynova/flydrive/build/exceptions/InvalidConfig.js:16:16)
     at StorageManager.disk (/directus/node_modules/@slynova/flydrive/build/StorageManager.js:57:46)
     at /directus/node_modules/directus/dist/controllers/assets.js:47:48
     at Generator.next (<anonymous>)
     at fulfilled (/directus/node_modules/directus/dist/controllers/assets.js:5:58)
     at processTicksAndRejections (internal/process/task_queues.js:93:5)
20:33:57 ✨ request errored GET 500 /assets/eb331ef9-0f8d-4c96-baae-3f1431e2a7c2?key=system-medium-cover&modified=2020-10-30T20:55:40Z&access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU2MGM4MWRjLTE2NWEtNDc5MC1iY2VhLTBhNjM1MTdhYzhjMyIsImlhdCI6MTYwNTM4NjAzNiwiZXhwIjoxNjA1Mzg2OTM2fQ.LtpwjYjoJ6J0h9TQWjPy4fTDWvIxLLrroRABuNUaUNM 36ms

**Comment by rijkvanzanten** [comment]
Are you sure those env vars are passed on to Directus correctly? 🤔 (just thinking aloud here)
