### ISSUE TITLE
Unable to install Directus on MySQL: ER_CANNOT_ADD_FOREIGN: Cannot add foreign key constraint 

### ISSUE THREAD

**Issue by metalmarco** [directus/next#915]
- Directus RC8
- DB: tested on MySQL, Aurora MySQL and MariaDB

Steps to reproduce:
- npx create-directus-project my-project
- Set database endpoint/credentials

Error:

```
[ER_CANNOT_ADD_FOREIGN] alter table `directus_fields` add constraint `directus_fields_group_foreign` foreign key (`group`) references `directus_fields` (`id`) on update CASCADE on delete SET DEFAULT - ER_CANNOT_ADD_FOREIGN: Cannot add foreign key constraint
```

I think the problems is that it's trying to create a foreing key between directus_fields.group (INT 10) and directus_files.id (CHAR 36)

**Comment by rijkvanzanten** [comment]
@metalmarco I think you misread `references `directus_fields` (`id`)` for `directus_files`

**Comment by atslab** [comment]
I'm getting the same error.

**Comment by Kinzi** [comment]
I'm getting something very related on `npx directus database migrate:latest`

```
Running migrations...Error: ER_CANT_DROP_FIELD_OR_KEY: Can't DROP 'directus_fields_group_foreign'; check that column/key exists
    at Query.Sequence._packetToError (/Users/seb/Code/cms/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/seb/Code/cms/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/seb/Code/cms/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/seb/Code/cms/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/seb/Code/cms/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/seb/Code/cms/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/seb/Code/cms/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/seb/Code/cms/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    --------------------
    at Protocol._enqueue (/Users/seb/Code/cms/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/Users/seb/Code/cms/node_modules/mysql/lib/Connection.js:198:25)
    at /Users/seb/Code/cms/node_modules/knex/lib/dialects/mysql/index.js:134:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/Users/seb/Code/cms/node_modules/knex/lib/dialects/mysql/index.js:128:12)
    at Client_MySQL.query (/Users/seb/Code/cms/node_modules/knex/lib/client.js:168:17)
    at Runner.query (/Users/seb/Code/cms/node_modules/knex/lib/runner.js:151:36)
    at Runner.queryArray (/Users/seb/Code/cms/node_modules/knex/lib/runner.js:248:31)
    at /Users/seb/Code/cms/node_modules/knex/lib/runner.js:38:25
    at /Users/seb/Code/cms/node_modules/knex/lib/runner.js:277:24 {
  code: 'ER_CANT_DROP_FIELD_OR_KEY',
  errno: 1091,
  sqlMessage: "Can't DROP 'directus_fields_group_foreign'; check that column/key exists",
  sqlState: '42000',
  index: 0,
  sql: 'alter table `directus_fields` drop foreign key `directus_fields_group_foreign`'
```

**Comment by rijkvanzanten** [comment]
@Kinzi Feels similar to me!

**Comment by metalmarco** [comment]
Tested on directus@9.0.0-rc.10

```
marco@MacBook-Pro-di-Marco directus9 % npx create-directus-project my-project
npx: installato 46 in 4.657s
? Choose your database client MySQL / MariaDB / Aurora
? Database Host: xxxxxxxxxxx
? Port: xxxxxxx
? Database Name: xxxxxxxx
? Database User: xxxxxxx
? Database Password: ****************************

Something went wrong while seeding the database:

[ER_CANT_CREATE_TABLE] alter table `directus_fields` add constraint `directus_fields_group_foreign` foreign key (`group`) references `directus_fields` (`id`) on update CASCADE on delete SET DEFAULT - ER_CANT_CREATE_TABLE: Can't create table `directus9`.`directus_fields` (errno: 150 "Foreign key constraint is incorrectly formed")

Please try again
```

**Comment by rijkvanzanten** [comment]
I believe I found the source of the problem here, I'm using `SET DEFAULT` for on delete for this constraint, but it looks like only certain MySQL- drivers support this. It doesn't seem to be a problem (on my end) in MySQL (proper) 8.x, but running it under InnoDB or MariaDB seems to start causing issues

**Comment by Kinzi** [comment]
It's should be proper mysql in my case...

**Comment by rijkvanzanten** [comment]
@Kinzi I don't know! 🤷 I just came across this in the MySQL reference:

![CleanShot 2020-11-10 at 12 44 43](https://user-images.githubusercontent.com/9141017/98711087-8aecd780-2352-11eb-9832-e06984ecdf6c.png)


https://dev.mysql.com/doc/refman/8.0/en/create-table-foreign-keys.html

**Comment by Kinzi** [comment]
@rijkvanzanten unfortunately I still get the very same error as above with rc13 running `npx directus database migrate:latest`. Shall I open a new issue?

**Comment by metalmarco** [comment]
> @rijkvanzanten unfortunately I still get the very same error as above with rc13 running `npx directus database migrate:latest`. Shall I open a new issue?

I can confirm, instead, that my problem has been fixed (clean installation on MySQL, no migration)

**Comment by rijkvanzanten** [comment]
@Kinzi I think your issue is related, but not the same as the OP. Feel free to open a new issue 👍
