### ISSUE TITLE
Building Directus results in a ton of errors

### ISSUE THREAD

**Issue by Fusseldieb** [directus/next#923]
Hi there,
I wanted to see what v9 looks like and maybe even help on some things, but when I tried to "npm run dev", I ran in some trouble.

I downloaded the ZIP from this repo, installed node v14.15.0, then ran npm install (which succeeded), then tried to "npm run dev", which resulted in:

```
Valentino@VALENTINO-PC MINGW64 ~/Desktop/next-main
$ npm run dev

> directus-monorepo@ dev C:\Users\Valentino\Desktop\next-main
> lerna run dev --stream --parallel

lerna notice cli v3.22.1
lerna info Executing command in 4 packages: "npm run dev"
directus: > directus@9.0.0-rc.8 dev C:\Users\Valentino\Desktop\next-main\api
directus: > cross-env NODE_ENV=development LOG_LEVEL=trace ts-node-dev --files src/start.ts --respawn --watch "src/**/*.ts" --transpile-only
@directus/app: > @directus/app@9.0.0-rc.8 dev C:\Users\Valentino\Desktop\next-main\app
@directus/app: > vue-cli-service serve
@directus/docs: > @directus/docs@9.0.0-rc.8 dev C:\Users\Valentino\Desktop\next-main\docs
@directus/docs: > npm-watch build
@directus/specs: > @directus/specs@9.0.0-rc.8 dev C:\Users\Valentino\Desktop\next-main\packages\spec
@directus/specs: > npm-watch build
directus: [INFO] 10:32:04 ts-node-dev ver. 1.0.0 (using ts-node ver. 9.0.0, typescript ver. 3.9.7)
@directus/app:  INFO  Starting development server...
@directus/docs: Building docs...
@directus/docs: Built docs in 121 ms
@directus/specs: Created dist\openapi.json from specs/openapi.yaml
@directus/app: Starting type checking service...
@directus/app: Using 1 worker with 2048MB memory limit
directus: (node:9860) UnhandledPromiseRejectionWarning: Error: knex: Required configuration option 'client' is missing.
directus:     at new Client (C:\Users\Valentino\Desktop\next-main\node_modules\knex\lib\client.js:54:11)
directus:     at Object.Knex [as default] (C:\Users\Valentino\Desktop\next-main\node_modules\knex\lib\knex.js:53:28)
directus:     at Object.<anonymous> (C:\Users\Valentino\Desktop\next-main\api\src\database\index.ts:47:22)
directus:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
directus:     at Module._compile (C:\Users\Valentino\Desktop\next-main\node_modules\source-map-support\source-map-support.js:547:25)
directus:     at Module.m._compile (C:\Users\VALENT~1\AppData\Local\Temp\ts-node-dev-hook-8387129263146487.js:57:33)
directus:     at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
directus:     at require.extensions.<computed> (C:\Users\VALENT~1\AppData\Local\Temp\ts-node-dev-hook-8387129263146487.js:59:20)
directus:     at Object.nodeDevHook [as .ts] (C:\Users\Valentino\Desktop\next-main\node_modules\ts-node-dev\lib\hook.js:63:13)
directus:     at Module.load (internal/modules/cjs/loader.js:928:32)
directus: (Use `node --trace-warnings ...` to show where the warning was created)
directus: (node:9860) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
directus: (node:9860) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
@directus/app:  ERROR  Failed to compile with 8 errors10:32:19
@directus/app: This dependency was not found:
@directus/app: * @directus/format-title in ../node_modules/cache-loader/dist/cjs.js??ref--13-0!../node_modules/babel-loader/lib!../node_modules/ts-loader??ref--13-2!../node_modules/cache-loader/dist/cjs.js??ref--0-0!../node_modules/vue-loader/lib??vue-loader-options!./src/components/v-field-template/field-list-item.vue?vue&type=script&lang=ts&, ../node_modules/cache-loader/dist/cjs.js??ref--13-0!../node_modules/babel-loader/lib!../node_modules/ts-loader??ref--13-2!../node_modules/cache-loader/dist/cjs.js??ref--0-0!../node_modules/vue-loader/lib??vue-loader-options!./src/displays/formatted-value/formatted-value.vue?vue&type=script&lang=ts& and 6 others
@directus/app: To install it, you can run: npm install --save @directus/format-title
@directus/app: Type checking in progress...
@directus/app:  WAIT  Compiling...10:32:20
@directus/app: Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'
@directus/app:  ERROR  Failed to compile with 8 errors10:32:24
@directus/app: This dependency was not found:
@directus/app: * @directus/format-title in ../node_modules/cache-loader/dist/cjs.js??ref--13-0!../node_modules/babel-loader/lib!../node_modules/ts-loader??ref--13-2!../node_modules/cache-loader/dist/cjs.js??ref--0-0!../node_modules/vue-loader/lib??vue-loader-options!./src/components/v-field-template/field-list-item.vue?vue&type=script&lang=ts&, ../node_modules/cache-loader/dist/cjs.js??ref--13-0!../node_modules/babel-loader/lib!../node_modules/ts-loader??ref--13-2!../node_modules/cache-loader/dist/cjs.js??ref--0-0!../node_modules/vue-loader/lib??vue-loader-options!./src/displays/formatted-value/formatted-value.vue?vue&type=script&lang=ts& and 6 others
@directus/app: To install it, you can run: npm install --save @directus/format-title
@directus/app: Type checking in progress...
@directus/app:  WAIT  Compiling...10:32:24
@directus/app:  ERROR  Failed to compile with 8 errors10:32:25
@directus/app: This dependency was not found:
@directus/app: * @directus/format-title in ../node_modules/cache-loader/dist/cjs.js??ref--13-0!../node_modules/babel-loader/lib!../node_modules/ts-loader??ref--13-2!../node_modules/cache-loader/dist/cjs.js??ref--0-0!../node_modules/vue-loader/lib??vue-loader-options!./src/components/v-field-template/field-list-item.vue?vue&type=script&lang=ts&, ../node_modules/cache-loader/dist/cjs.js??ref--13-0!../node_modules/babel-loader/lib!../node_modules/ts-loader??ref--13-2!../node_modules/cache-loader/dist/cjs.js??ref--0-0!../node_modules/vue-loader/lib??vue-loader-options!./src/displays/formatted-value/formatted-value.vue?vue&type=script&lang=ts& and 6 others
@directus/app: To install it, you can run: npm install --save @directus/format-title
@directus/app: Type checking in progress...
@directus/app: ERROR in C:/Users/Valentino/Desktop/next-main/app/src/components/v-field-template/field-list-item.vue(25,25):
@directus/app: 25:25 Cannot find module '@directus/format-title' or its corresponding type declarations.
@directus/app:     23 | import { defineComponent, PropType } from '@vue/composition-api';
@directus/app:     24 | import { FieldTree } from './types';
@directus/app:   > 25 | import formatTitle from '@directus/format-title';
@directus/app:        |                         ^
@directus/app:     26 |
@directus/app:     27 | export default defineComponent({
@directus/app:     28 |         name: 'field-list-item',
@directus/app: Version: typescript 3.9.7
@directus/app: Time: 14808ms
@directus/app: ERROR in C:/Users/Valentino/Desktop/next-main/app/src/displays/color/color.vue(10,25):
@directus/app: 10:25 Cannot find module '@directus/format-title' or its corresponding type declarations.
@directus/app:      8 | <script lang="ts">
@directus/app:      9 | import { defineComponent, computed, PropType } from '@vue/composition-api';
@directus/app:   > 10 | import formatTitle from '@directus/format-title';
@directus/app:        |                         ^
@directus/app:     11 | import Color from 'color';
@directus/app:     12 | import { isHex } from '@/utils/color';
@directus/app:     13 |
@directus/app: ERROR in C:/Users/Valentino/Desktop/next-main/app/src/displays/formatted-value/formatted-value.vue(11,25):
@directus/app: 11:25 Cannot find module '@directus/format-title' or its corresponding type declarations.
@directus/app:      9 | <script lang="ts">
@directus/app:     10 | import { defineComponent, computed } from '@vue/composition-api';
@directus/app:   > 11 | import formatTitle from '@directus/format-title';
@directus/app:        |                         ^
@directus/app:     12 |
@directus/app:     13 | export default defineComponent({
@directus/app:     14 |         props: {
@directus/app: ERROR in C:/Users/Valentino/Desktop/next-main/app/src/displays/labels/labels.vue(32,25):
@directus/app: 32:25 Cannot find module '@directus/format-title' or its corresponding type declarations.
@directus/app:     30 | <script lang="ts">
@directus/app:     31 | import { defineComponent, computed, PropType } from '@vue/composition-api';
@directus/app:   > 32 | import formatTitle from '@directus/format-title';
@directus/app:        |                         ^
@directus/app:     33 |
@directus/app:     34 | type Choice = {
@directus/app:     35 |         value: string;
@directus/app: ERROR in C:/Users/Valentino/Desktop/next-main/app/src/interfaces/code/code.vue(28,25):
@directus/app: 28:25 Cannot find module '@directus/format-title' or its corresponding type declarations.
@directus/app:     26 | import 'codemirror/keymap/sublime.js';
@directus/app:     27 |
@directus/app:   > 28 | import formatTitle from '@directus/format-title';
@directus/app:        |                         ^
@directus/app:     29 |
@directus/app:     30 | export default defineComponent({
@directus/app:     31 |         props: {
@directus/app: ERROR in C:/Users/Valentino/Desktop/next-main/app/src/interfaces/icon/icon.vue(51,25):
@directus/app: 51:25 Cannot find module '@directus/format-title' or its corresponding type declarations.
@directus/app:     49 | import icons from './icons.json';
@directus/app:     50 | import { defineComponent, ref, computed } from '@vue/composition-api';
@directus/app:   > 51 | import formatTitle from '@directus/format-title';
@directus/app:        |                         ^
@directus/app:     52 |
@directus/app:     53 | export default defineComponent({
@directus/app:     54 |         props: {
@directus/app: ERROR in C:/Users/Valentino/Desktop/next-main/app/src/interfaces/tags/tags.vue(46,25):
@directus/app: 46:25 Cannot find module '@directus/format-title' or its corresponding type declarations.
@directus/app:     44 | <script lang="ts">
@directus/app:     45 | import { defineComponent, PropType, ref, computed, watch } from '@vue/composition-api';
@directus/app:   > 46 | import formatTitle from '@directus/format-title';
@directus/app:        |                         ^
@directus/app:     47 |
@directus/app:     48 | export default defineComponent({
@directus/app:     49 |         props: {
@directus/app: ERROR in C:/Users/Valentino/Desktop/next-main/app/src/stores/collections.ts(7,25):
@directus/app: 7:25 Cannot find module '@directus/format-title' or its corresponding type declarations.
@directus/app:      5 | import { notEmpty } from '@/utils/is-empty/';
@directus/app:      6 | import VueI18n from 'vue-i18n';
@directus/app:   >  7 | import formatTitle from '@directus/format-title';
@directus/app:        |                         ^
@directus/app:      8 | import { notify } from '@/utils/notify';
@directus/app:      9 | import { unexpectedError } from '@/utils/unexpected-error';
@directus/app:     10 |
@directus/app: ERROR in C:/Users/Valentino/Desktop/next-main/app/src/stores/fields.ts(6,25):
@directus/app: 6:25 Cannot find module '@directus/format-title' or its corresponding type declarations.
@directus/app:     4 | import { notEmpty } from '@/utils/is-empty/';
@directus/app:     5 | import { i18n } from '@/lang';
@directus/app:   > 6 | import formatTitle from '@directus/format-title';
@directus/app:       |                         ^
@directus/app:     7 | import { useRelationsStore } from '@/stores/';
@directus/app:     8 | import { Relation, FieldRaw, Field } from '@/types';
@directus/app:     9 | import { merge } from 'lodash';
```

Any clue on what I'm doing wrong here?

EDIT: What I'm seeing a lot is:
`Cannot find module '@directus/format-title' or its corresponding type declarations.`
Should I try and install this module(?) separately? And if yes, why doesn't it come specified in package.json (dev-deps) so it gets installed automatically?
I mean, I don't even know if that would solve it. There are a lot of other errors too.

Also, if more information is needed, let me know.

EDIT: `git clone <repo>` instead of downloading the ZIP results in the same errors.

Thanks in advance!!

**Comment by benhaynes** [comment]
We'll get some info to you shortly... in the meantime, maybe this will help?

https://github.com/directus/next/blob/main/docs/getting-started/contributing.md#development-workflow

If not, we'll get these Docs updated so this issue can be avoided in the future.

**Comment by Fusseldieb** [comment]
Thanks for the fast response!

I didn't see the `contributing.md` for some reason, but now that I did, I deleted the folder and started clean, cloning the repo and following the steps as in `contributing.md`.

What I think lacks in the documentation is about modifying the `.env` file, it doesn't say if I should rename it or similar. Since I had no pointers, I just opened it and commented the MySQL connection and uncommented `DB_FILENAME="./data.db"`.

I then ran it using `npm run dev` and the same errors appeared again. No change whatsoever.

**Comment by rijkvanzanten** [comment]
I've updated this in #926 👍 It'll now do a single build right after running `npm install` to ensure all subdependencies are built

**Comment by Fusseldieb** [comment]
Solved! 

Cloned clean from `directus/next` and now it ran without an issue.

I really appreciate your dedication! 🥇 

Thank you!

**Comment by rijkvanzanten** [comment]
Thanks @Fusseldieb! Means a lot ❤️
