### ISSUE TITLE
Not able to run migrations on other PG schemas than public

### ISSUE THREAD

**Issue by danieljwestman** [directus/next#928]
Directus v9-rc.8
Latest commit 0bcc2c1
PG 12
Clean and fresh install

Not possible to run migrations if the schema (search_path) isn't "public".

`npx directus database migration:latest`

Throws error:

```
⠋ Running migrations...error: alter table "directus_fields" drop constraint "directus_fields_collection_foreign" - constraint "directus_fields_collection_foreign" of relation "directus_fields" does not exist
    at Parser.parseErrorMessage (/api/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/api/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/api/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/api/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:307:12)
    at readableAddChunk (_stream_readable.js:282:9)
    at Socket.Readable.push (_stream_readable.js:221:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 162,
  severity: 'ERROR',
  code: '42704',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'tablecmds.c',
  line: '10179',
  routine: 'ATExecDropConstraint'
}

```

But it works when I change the search_path to "public" in env.

**Comment by rijkvanzanten** [comment]
I believe this was fixed in https://github.com/directus/next/pull/926. I'm able to run both `database install` and `database migrate:latest` using a non-`public` search path in my .env in rc12 :slig

**Comment by danieljwestman** [comment]
Okay, I'll give another try 👍🏻
